// Description: This file contains all the descriptions used in the application.

import { StageEnum, HelpSection } from "../types"

// Bridge.tsx
export const bridgeTitle = "Bridge"
export const bridgeDescriptionLine1 = "Bridge your Ethereum to OEV Network."
export const bridgeDescriptionLine2 = "You can add funds to your wallet by using the official OEV Network bridge."

export const oevNetworkBalance = "OEV Network Balance"
export const ethereumBalance = "Ethereum Balance"

export const noBalanceTitle = "Add Funds"
export const noBalanceDescription = "You have no funds to deposit. Please add funds to your wallet."

export const bridgeButton = "OEV Network Bridge"

// Deposit.tsx
export const depositCollateralTitle = "Deposit Collateral"
export const depositCollateralDescription = "Deposit your OEV Network Ethereum to start placing bids."

export const collateralBalance = "Collateral Balance"
export const depositCollateralButton = "Deposit Collateral"

// PlaceBid.tsx

export const placeBidTitle = "Place a Bid"
export const placeBidDescription = "Places bids in anticipation of an OEV opportunity on a specific dapi."

export const selectChainAndDapiDescription = "Select Chain and dApi"
export const bidAmountDescription = "I want to bid"
export const bidConditionDescription = "for an update that satisfies the condition"

export const switchToBid = "Switch to OEV Network to Place a Bid"

export const insufficientBalance = (chainName: string, balance: string, symbol: string) => `Insufficient balance on ${chainName} chain with ${balance} ${symbol}`
export const insufficientCollateral = "Insufficient collateral. Please deposit more collateral"

export const extendedLTE = "Less than or equal to"
export const extendedGTE = "Greater than or equal to"

export const bidPlacedTitle = "Proceed to Update dApi"
export const bidPlacedMessage = "Your bid has been placed. Please proceed to next stage"

export const placeBidButton = "Place Bid"

// AwardUpdate.tsx

export const awardUpdateTitle = "Award and Update"
export const awardUpdateDescription = "The bid has been accepted. The auctioneer will assess all bids and award the auction to the highest bidder."

export const feeDeductionTitle = (fee: string) => `If your bid is awarded, a fee of ${fee} ETH will be deducted.`

export const proceedToReportTitle = "Proceed to Report"
export const proceedToReportStage = "dAPI has been updated. Please proceed to next stage"

// Report.tsx

export const reportTitle = "Report Fullfillment"
export const reportDescription = "dAPI has been updated. Please report fullfillment."

export const collateralBalanceBeforeReport = "Collateral Balance Before Report"
export const collateralBalanceAfterReport = "Collateral Balance After Report"

export const feeDeductionRefundDefault = "Once the fullfillment is confirmed or contradicted, your collateral amount will be updated."
export const feeDeductionRefundConfirmed = (fee: string) => `Your fullfillment is confirmed, your collareral amount released and the protocol fee is charged. ${fee} ETH is returned.`
export const feeDeductionRefundContradicted = (fee: string) => `Your fullfillment is contradicted, your collareral amount is slashed and the protocol fee is refunded. ${fee} ETH is returned.`

//HELP TEXT

export const helpTitle = (stage: StageEnum) => {
    switch (stage) {
        case StageEnum.Bridge:
            return "Bridging Ethereum to OEV Network"
        case StageEnum.Deposit:
            return "Depositing OEV Network Ethereum"
        case StageEnum.PlaceBid:
            return "Placing Bids"
        case StageEnum.AwardAndUpdate:
            return "Awarding Bids and dApi Update"
        case StageEnum.Report:
            return "Reporting Fullfillment"
        default:
            return "Help"
    }
}

export const helpText = (stage: StageEnum) => {
    switch (stage) {
        case StageEnum.Bridge:
            return [
                {
                    title: "Help Section 1",
                    content: [
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent interdum placerat justo sit amet viverra. Nullam eget justo sed lacus malesuada scelerisque sed venenatis odio. Pellentesque convallis consectetur dui, quis pellentesque felis consectetur at. Mauris sem elit, tempus vel ligula a, ultricies pellentesque purus. Cras ullamcorper lacinia nisi, vel ornare augue bibendum consequat. Mauris nec molestie dolor. Nullam luctus tortor scelerisque ligula venenatis, vitae malesuada magna pulvinar. Pellentesque et arcu vel felis bibendum tristique. Donec a interdum eros. In molestie purus sollicitudin enim lacinia eleifend. Sed suscipit vehicula felis a lacinia",
                        "Vestibulum quis elit sapien. Quisque maximus auctor varius. Maecenas egestas dolor nulla. Fusce vitae dui non risus malesuada interdum eget id nisl. Nunc suscipit luctus ipsum, nec luctus orci vestibulum ac. Proin pharetra venenatis sollicitudin. Phasellus viverra leo sed pellentesque convallis. Maecenas cursus ultricies neque, vel vestibulum ex eleifend vitae. Curabitur ornare nisi sed convallis condimentum. Cras condimentum ullamcorper varius. Ut quis rhoncus nulla, sit amet aliquam odio. Nullam tincidunt, augue eget tincidunt finibus, eros metus ultrices magna, sed ultricies nisi nisl eget risus. Phasellus pulvinar risus id metus facilisis vulputate. Integer aliquet, ligula consequat ullamcorper condimentum, magna eros pellentesque eros, sed pharetra ligula diam eu nisi. Nulla ut lectus massa. Nulla vitae quam hendrerit, porttitor turpis sed, maximus lacus",
                        "Proin pulvinar lacus tempus vulputate euismod. Mauris nisl arcu, molestie eget varius id, dapibus ac metus. Nam aliquam, massa sed porttitor accumsan, eros magna lobortis lacus, non accumsan dui magna porttitor ligula. Suspendisse maximus laoreet ante vitae porttitor. Nulla tincidunt augue eget elementum luctus. Vivamus tincidunt quam nec ipsum sollicitudin vulputate. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In venenatis, eros eget tristique tincidunt, metus leo egestas nibh, vitae tincidunt nisl diam nec metus. Suspendisse potenti. Proin eget ex ullamcorper odio malesuada bibendum ac nec orci. Sed convallis ex sed elit ultrices ullamcorper. Maecenas fermentum consectetur purus id tincidunt."
                    ]
                } as HelpSection,
                {
                    title: "Help Section 2",
                    content: [
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent interdum placerat justo sit amet viverra. Nullam eget justo sed lacus malesuada scelerisque sed venenatis odio. Pellentesque convallis consectetur dui, quis pellentesque felis consectetur at. Mauris sem elit, tempus vel ligula a, ultricies pellentesque purus. Cras ullamcorper lacinia nisi, vel ornare augue bibendum consequat. Mauris nec molestie dolor. Nullam luctus tortor scelerisque ligula venenatis, vitae malesuada magna pulvinar. Pellentesque et arcu vel felis bibendum tristique. Donec a interdum eros. In molestie purus sollicitudin enim lacinia eleifend. Sed suscipit vehicula felis a lacinia",
                        "Vestibulum quis elit sapien. Quisque maximus auctor varius. Maecenas egestas dolor nulla. Fusce vitae dui non risus malesuada interdum eget id nisl. Nunc suscipit luctus ipsum, nec luctus orci vestibulum ac. Proin pharetra venenatis sollicitudin. Phasellus viverra leo sed pellentesque convallis. Maecenas cursus ultricies neque, vel vestibulum ex eleifend vitae. Curabitur ornare nisi sed convallis condimentum. Cras condimentum ullamcorper varius. Ut quis rhoncus nulla, sit amet aliquam odio. Nullam tincidunt, augue eget tincidunt finibus, eros metus ultrices magna, sed ultricies nisi nisl eget risus. Phasellus pulvinar risus id metus facilisis vulputate. Integer aliquet, ligula consequat ullamcorper condimentum, magna eros pellentesque eros, sed pharetra ligula diam eu nisi. Nulla ut lectus massa. Nulla vitae quam hendrerit, porttitor turpis sed, maximus lacus",
                        "Proin pulvinar lacus tempus vulputate euismod. Mauris nisl arcu, molestie eget varius id, dapibus ac metus. Nam aliquam, massa sed porttitor accumsan, eros magna lobortis lacus, non accumsan dui magna porttitor ligula. Suspendisse maximus laoreet ante vitae porttitor. Nulla tincidunt augue eget elementum luctus. Vivamus tincidunt quam nec ipsum sollicitudin vulputate. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In venenatis, eros eget tristique tincidunt, metus leo egestas nibh, vitae tincidunt nisl diam nec metus. Suspendisse potenti. Proin eget ex ullamcorper odio malesuada bibendum ac nec orci. Sed convallis ex sed elit ultrices ullamcorper. Maecenas fermentum consectetur purus id tincidunt."
                    ]
                } as HelpSection, {
                    title: "Help Section 3",
                    content: [
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent interdum placerat justo sit amet viverra. Nullam eget justo sed lacus malesuada scelerisque sed venenatis odio. Pellentesque convallis consectetur dui, quis pellentesque felis consectetur at. Mauris sem elit, tempus vel ligula a, ultricies pellentesque purus. Cras ullamcorper lacinia nisi, vel ornare augue bibendum consequat. Mauris nec molestie dolor. Nullam luctus tortor scelerisque ligula venenatis, vitae malesuada magna pulvinar. Pellentesque et arcu vel felis bibendum tristique. Donec a interdum eros. In molestie purus sollicitudin enim lacinia eleifend. Sed suscipit vehicula felis a lacinia",
                        "Vestibulum quis elit sapien. Quisque maximus auctor varius. Maecenas egestas dolor nulla. Fusce vitae dui non risus malesuada interdum eget id nisl. Nunc suscipit luctus ipsum, nec luctus orci vestibulum ac. Proin pharetra venenatis sollicitudin. Phasellus viverra leo sed pellentesque convallis. Maecenas cursus ultricies neque, vel vestibulum ex eleifend vitae. Curabitur ornare nisi sed convallis condimentum. Cras condimentum ullamcorper varius. Ut quis rhoncus nulla, sit amet aliquam odio. Nullam tincidunt, augue eget tincidunt finibus, eros metus ultrices magna, sed ultricies nisi nisl eget risus. Phasellus pulvinar risus id metus facilisis vulputate. Integer aliquet, ligula consequat ullamcorper condimentum, magna eros pellentesque eros, sed pharetra ligula diam eu nisi. Nulla ut lectus massa. Nulla vitae quam hendrerit, porttitor turpis sed, maximus lacus",
                        "Proin pulvinar lacus tempus vulputate euismod. Mauris nisl arcu, molestie eget varius id, dapibus ac metus. Nam aliquam, massa sed porttitor accumsan, eros magna lobortis lacus, non accumsan dui magna porttitor ligula. Suspendisse maximus laoreet ante vitae porttitor. Nulla tincidunt augue eget elementum luctus. Vivamus tincidunt quam nec ipsum sollicitudin vulputate. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In venenatis, eros eget tristique tincidunt, metus leo egestas nibh, vitae tincidunt nisl diam nec metus. Suspendisse potenti. Proin eget ex ullamcorper odio malesuada bibendum ac nec orci. Sed convallis ex sed elit ultrices ullamcorper. Maecenas fermentum consectetur purus id tincidunt."
                    ]
                } as HelpSection, {
                    title: "Help Section 4",
                    content: [
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent interdum placerat justo sit amet viverra. Nullam eget justo sed lacus malesuada scelerisque sed venenatis odio. Pellentesque convallis consectetur dui, quis pellentesque felis consectetur at. Mauris sem elit, tempus vel ligula a, ultricies pellentesque purus. Cras ullamcorper lacinia nisi, vel ornare augue bibendum consequat. Mauris nec molestie dolor. Nullam luctus tortor scelerisque ligula venenatis, vitae malesuada magna pulvinar. Pellentesque et arcu vel felis bibendum tristique. Donec a interdum eros. In molestie purus sollicitudin enim lacinia eleifend. Sed suscipit vehicula felis a lacinia",
                        "Vestibulum quis elit sapien. Quisque maximus auctor varius. Maecenas egestas dolor nulla. Fusce vitae dui non risus malesuada interdum eget id nisl. Nunc suscipit luctus ipsum, nec luctus orci vestibulum ac. Proin pharetra venenatis sollicitudin. Phasellus viverra leo sed pellentesque convallis. Maecenas cursus ultricies neque, vel vestibulum ex eleifend vitae. Curabitur ornare nisi sed convallis condimentum. Cras condimentum ullamcorper varius. Ut quis rhoncus nulla, sit amet aliquam odio. Nullam tincidunt, augue eget tincidunt finibus, eros metus ultrices magna, sed ultricies nisi nisl eget risus. Phasellus pulvinar risus id metus facilisis vulputate. Integer aliquet, ligula consequat ullamcorper condimentum, magna eros pellentesque eros, sed pharetra ligula diam eu nisi. Nulla ut lectus massa. Nulla vitae quam hendrerit, porttitor turpis sed, maximus lacus",
                        "Proin pulvinar lacus tempus vulputate euismod. Mauris nisl arcu, molestie eget varius id, dapibus ac metus. Nam aliquam, massa sed porttitor accumsan, eros magna lobortis lacus, non accumsan dui magna porttitor ligula. Suspendisse maximus laoreet ante vitae porttitor. Nulla tincidunt augue eget elementum luctus. Vivamus tincidunt quam nec ipsum sollicitudin vulputate. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In venenatis, eros eget tristique tincidunt, metus leo egestas nibh, vitae tincidunt nisl diam nec metus. Suspendisse potenti. Proin eget ex ullamcorper odio malesuada bibendum ac nec orci. Sed convallis ex sed elit ultrices ullamcorper. Maecenas fermentum consectetur purus id tincidunt."
                    ]
                } as HelpSection,
            ]
        case StageEnum.Deposit:
            return [
                {
                    title: "Help Section 1",
                    content: [
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent interdum placerat justo sit amet viverra. Nullam eget justo sed lacus malesuada scelerisque sed venenatis odio. Pellentesque convallis consectetur dui, quis pellentesque felis consectetur at. Mauris sem elit, tempus vel ligula a, ultricies pellentesque purus. Cras ullamcorper lacinia nisi, vel ornare augue bibendum consequat. Mauris nec molestie dolor. Nullam luctus tortor scelerisque ligula venenatis, vitae malesuada magna pulvinar. Pellentesque et arcu vel felis bibendum tristique. Donec a interdum eros. In molestie purus sollicitudin enim lacinia eleifend. Sed suscipit vehicula felis a lacinia",
                        "Vestibulum quis elit sapien. Quisque maximus auctor varius. Maecenas egestas dolor nulla. Fusce vitae dui non risus malesuada interdum eget id nisl. Nunc suscipit luctus ipsum, nec luctus orci vestibulum ac. Proin pharetra venenatis sollicitudin. Phasellus viverra leo sed pellentesque convallis. Maecenas cursus ultricies neque, vel vestibulum ex eleifend vitae. Curabitur ornare nisi sed convallis condimentum. Cras condimentum ullamcorper varius. Ut quis rhoncus nulla, sit amet aliquam odio. Nullam tincidunt, augue eget tincidunt finibus, eros metus ultrices magna, sed ultricies nisi nisl eget risus. Phasellus pulvinar risus id metus facilisis vulputate. Integer aliquet, ligula consequat ullamcorper condimentum, magna eros pellentesque eros, sed pharetra ligula diam eu nisi. Nulla ut lectus massa. Nulla vitae quam hendrerit, porttitor turpis sed, maximus lacus",
                        "Proin pulvinar lacus tempus vulputate euismod. Mauris nisl arcu, molestie eget varius id, dapibus ac metus. Nam aliquam, massa sed porttitor accumsan, eros magna lobortis lacus, non accumsan dui magna porttitor ligula. Suspendisse maximus laoreet ante vitae porttitor. Nulla tincidunt augue eget elementum luctus. Vivamus tincidunt quam nec ipsum sollicitudin vulputate. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In venenatis, eros eget tristique tincidunt, metus leo egestas nibh, vitae tincidunt nisl diam nec metus. Suspendisse potenti. Proin eget ex ullamcorper odio malesuada bibendum ac nec orci. Sed convallis ex sed elit ultrices ullamcorper. Maecenas fermentum consectetur purus id tincidunt."
                    ]
                } as HelpSection,
                {
                    title: "Help Section 2",
                    content: [
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent interdum placerat justo sit amet viverra. Nullam eget justo sed lacus malesuada scelerisque sed venenatis odio. Pellentesque convallis consectetur dui, quis pellentesque felis consectetur at. Mauris sem elit, tempus vel ligula a, ultricies pellentesque purus. Cras ullamcorper lacinia nisi, vel ornare augue bibendum consequat. Mauris nec molestie dolor. Nullam luctus tortor scelerisque ligula venenatis, vitae malesuada magna pulvinar. Pellentesque et arcu vel felis bibendum tristique. Donec a interdum eros. In molestie purus sollicitudin enim lacinia eleifend. Sed suscipit vehicula felis a lacinia",
                        "Vestibulum quis elit sapien. Quisque maximus auctor varius. Maecenas egestas dolor nulla. Fusce vitae dui non risus malesuada interdum eget id nisl. Nunc suscipit luctus ipsum, nec luctus orci vestibulum ac. Proin pharetra venenatis sollicitudin. Phasellus viverra leo sed pellentesque convallis. Maecenas cursus ultricies neque, vel vestibulum ex eleifend vitae. Curabitur ornare nisi sed convallis condimentum. Cras condimentum ullamcorper varius. Ut quis rhoncus nulla, sit amet aliquam odio. Nullam tincidunt, augue eget tincidunt finibus, eros metus ultrices magna, sed ultricies nisi nisl eget risus. Phasellus pulvinar risus id metus facilisis vulputate. Integer aliquet, ligula consequat ullamcorper condimentum, magna eros pellentesque eros, sed pharetra ligula diam eu nisi. Nulla ut lectus massa. Nulla vitae quam hendrerit, porttitor turpis sed, maximus lacus",
                        "Proin pulvinar lacus tempus vulputate euismod. Mauris nisl arcu, molestie eget varius id, dapibus ac metus. Nam aliquam, massa sed porttitor accumsan, eros magna lobortis lacus, non accumsan dui magna porttitor ligula. Suspendisse maximus laoreet ante vitae porttitor. Nulla tincidunt augue eget elementum luctus. Vivamus tincidunt quam nec ipsum sollicitudin vulputate. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In venenatis, eros eget tristique tincidunt, metus leo egestas nibh, vitae tincidunt nisl diam nec metus. Suspendisse potenti. Proin eget ex ullamcorper odio malesuada bibendum ac nec orci. Sed convallis ex sed elit ultrices ullamcorper. Maecenas fermentum consectetur purus id tincidunt."
                    ]
                } as HelpSection, {
                    title: "Help Section 3",
                    content: [
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent interdum placerat justo sit amet viverra. Nullam eget justo sed lacus malesuada scelerisque sed venenatis odio. Pellentesque convallis consectetur dui, quis pellentesque felis consectetur at. Mauris sem elit, tempus vel ligula a, ultricies pellentesque purus. Cras ullamcorper lacinia nisi, vel ornare augue bibendum consequat. Mauris nec molestie dolor. Nullam luctus tortor scelerisque ligula venenatis, vitae malesuada magna pulvinar. Pellentesque et arcu vel felis bibendum tristique. Donec a interdum eros. In molestie purus sollicitudin enim lacinia eleifend. Sed suscipit vehicula felis a lacinia",
                        "Vestibulum quis elit sapien. Quisque maximus auctor varius. Maecenas egestas dolor nulla. Fusce vitae dui non risus malesuada interdum eget id nisl. Nunc suscipit luctus ipsum, nec luctus orci vestibulum ac. Proin pharetra venenatis sollicitudin. Phasellus viverra leo sed pellentesque convallis. Maecenas cursus ultricies neque, vel vestibulum ex eleifend vitae. Curabitur ornare nisi sed convallis condimentum. Cras condimentum ullamcorper varius. Ut quis rhoncus nulla, sit amet aliquam odio. Nullam tincidunt, augue eget tincidunt finibus, eros metus ultrices magna, sed ultricies nisi nisl eget risus. Phasellus pulvinar risus id metus facilisis vulputate. Integer aliquet, ligula consequat ullamcorper condimentum, magna eros pellentesque eros, sed pharetra ligula diam eu nisi. Nulla ut lectus massa. Nulla vitae quam hendrerit, porttitor turpis sed, maximus lacus",
                        "Proin pulvinar lacus tempus vulputate euismod. Mauris nisl arcu, molestie eget varius id, dapibus ac metus. Nam aliquam, massa sed porttitor accumsan, eros magna lobortis lacus, non accumsan dui magna porttitor ligula. Suspendisse maximus laoreet ante vitae porttitor. Nulla tincidunt augue eget elementum luctus. Vivamus tincidunt quam nec ipsum sollicitudin vulputate. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In venenatis, eros eget tristique tincidunt, metus leo egestas nibh, vitae tincidunt nisl diam nec metus. Suspendisse potenti. Proin eget ex ullamcorper odio malesuada bibendum ac nec orci. Sed convallis ex sed elit ultrices ullamcorper. Maecenas fermentum consectetur purus id tincidunt."
                    ]
                } as HelpSection, {
                    title: "Help Section 4",
                    content: [
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent interdum placerat justo sit amet viverra. Nullam eget justo sed lacus malesuada scelerisque sed venenatis odio. Pellentesque convallis consectetur dui, quis pellentesque felis consectetur at. Mauris sem elit, tempus vel ligula a, ultricies pellentesque purus. Cras ullamcorper lacinia nisi, vel ornare augue bibendum consequat. Mauris nec molestie dolor. Nullam luctus tortor scelerisque ligula venenatis, vitae malesuada magna pulvinar. Pellentesque et arcu vel felis bibendum tristique. Donec a interdum eros. In molestie purus sollicitudin enim lacinia eleifend. Sed suscipit vehicula felis a lacinia",
                        "Vestibulum quis elit sapien. Quisque maximus auctor varius. Maecenas egestas dolor nulla. Fusce vitae dui non risus malesuada interdum eget id nisl. Nunc suscipit luctus ipsum, nec luctus orci vestibulum ac. Proin pharetra venenatis sollicitudin. Phasellus viverra leo sed pellentesque convallis. Maecenas cursus ultricies neque, vel vestibulum ex eleifend vitae. Curabitur ornare nisi sed convallis condimentum. Cras condimentum ullamcorper varius. Ut quis rhoncus nulla, sit amet aliquam odio. Nullam tincidunt, augue eget tincidunt finibus, eros metus ultrices magna, sed ultricies nisi nisl eget risus. Phasellus pulvinar risus id metus facilisis vulputate. Integer aliquet, ligula consequat ullamcorper condimentum, magna eros pellentesque eros, sed pharetra ligula diam eu nisi. Nulla ut lectus massa. Nulla vitae quam hendrerit, porttitor turpis sed, maximus lacus",
                        "Proin pulvinar lacus tempus vulputate euismod. Mauris nisl arcu, molestie eget varius id, dapibus ac metus. Nam aliquam, massa sed porttitor accumsan, eros magna lobortis lacus, non accumsan dui magna porttitor ligula. Suspendisse maximus laoreet ante vitae porttitor. Nulla tincidunt augue eget elementum luctus. Vivamus tincidunt quam nec ipsum sollicitudin vulputate. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In venenatis, eros eget tristique tincidunt, metus leo egestas nibh, vitae tincidunt nisl diam nec metus. Suspendisse potenti. Proin eget ex ullamcorper odio malesuada bibendum ac nec orci. Sed convallis ex sed elit ultrices ullamcorper. Maecenas fermentum consectetur purus id tincidunt."
                    ]
                } as HelpSection,
            ]
        case StageEnum.PlaceBid:
            return [
                {
                    title: "Help Section 1",
                    content: [
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent interdum placerat justo sit amet viverra. Nullam eget justo sed lacus malesuada scelerisque sed venenatis odio. Pellentesque convallis consectetur dui, quis pellentesque felis consectetur at. Mauris sem elit, tempus vel ligula a, ultricies pellentesque purus. Cras ullamcorper lacinia nisi, vel ornare augue bibendum consequat. Mauris nec molestie dolor. Nullam luctus tortor scelerisque ligula venenatis, vitae malesuada magna pulvinar. Pellentesque et arcu vel felis bibendum tristique. Donec a interdum eros. In molestie purus sollicitudin enim lacinia eleifend. Sed suscipit vehicula felis a lacinia",
                        "Vestibulum quis elit sapien. Quisque maximus auctor varius. Maecenas egestas dolor nulla. Fusce vitae dui non risus malesuada interdum eget id nisl. Nunc suscipit luctus ipsum, nec luctus orci vestibulum ac. Proin pharetra venenatis sollicitudin. Phasellus viverra leo sed pellentesque convallis. Maecenas cursus ultricies neque, vel vestibulum ex eleifend vitae. Curabitur ornare nisi sed convallis condimentum. Cras condimentum ullamcorper varius. Ut quis rhoncus nulla, sit amet aliquam odio. Nullam tincidunt, augue eget tincidunt finibus, eros metus ultrices magna, sed ultricies nisi nisl eget risus. Phasellus pulvinar risus id metus facilisis vulputate. Integer aliquet, ligula consequat ullamcorper condimentum, magna eros pellentesque eros, sed pharetra ligula diam eu nisi. Nulla ut lectus massa. Nulla vitae quam hendrerit, porttitor turpis sed, maximus lacus",
                        "Proin pulvinar lacus tempus vulputate euismod. Mauris nisl arcu, molestie eget varius id, dapibus ac metus. Nam aliquam, massa sed porttitor accumsan, eros magna lobortis lacus, non accumsan dui magna porttitor ligula. Suspendisse maximus laoreet ante vitae porttitor. Nulla tincidunt augue eget elementum luctus. Vivamus tincidunt quam nec ipsum sollicitudin vulputate. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In venenatis, eros eget tristique tincidunt, metus leo egestas nibh, vitae tincidunt nisl diam nec metus. Suspendisse potenti. Proin eget ex ullamcorper odio malesuada bibendum ac nec orci. Sed convallis ex sed elit ultrices ullamcorper. Maecenas fermentum consectetur purus id tincidunt."
                    ]
                } as HelpSection,
                {
                    title: "Help Section 2",
                    content: [
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent interdum placerat justo sit amet viverra. Nullam eget justo sed lacus malesuada scelerisque sed venenatis odio. Pellentesque convallis consectetur dui, quis pellentesque felis consectetur at. Mauris sem elit, tempus vel ligula a, ultricies pellentesque purus. Cras ullamcorper lacinia nisi, vel ornare augue bibendum consequat. Mauris nec molestie dolor. Nullam luctus tortor scelerisque ligula venenatis, vitae malesuada magna pulvinar. Pellentesque et arcu vel felis bibendum tristique. Donec a interdum eros. In molestie purus sollicitudin enim lacinia eleifend. Sed suscipit vehicula felis a lacinia",
                        "Vestibulum quis elit sapien. Quisque maximus auctor varius. Maecenas egestas dolor nulla. Fusce vitae dui non risus malesuada interdum eget id nisl. Nunc suscipit luctus ipsum, nec luctus orci vestibulum ac. Proin pharetra venenatis sollicitudin. Phasellus viverra leo sed pellentesque convallis. Maecenas cursus ultricies neque, vel vestibulum ex eleifend vitae. Curabitur ornare nisi sed convallis condimentum. Cras condimentum ullamcorper varius. Ut quis rhoncus nulla, sit amet aliquam odio. Nullam tincidunt, augue eget tincidunt finibus, eros metus ultrices magna, sed ultricies nisi nisl eget risus. Phasellus pulvinar risus id metus facilisis vulputate. Integer aliquet, ligula consequat ullamcorper condimentum, magna eros pellentesque eros, sed pharetra ligula diam eu nisi. Nulla ut lectus massa. Nulla vitae quam hendrerit, porttitor turpis sed, maximus lacus",
                        "Proin pulvinar lacus tempus vulputate euismod. Mauris nisl arcu, molestie eget varius id, dapibus ac metus. Nam aliquam, massa sed porttitor accumsan, eros magna lobortis lacus, non accumsan dui magna porttitor ligula. Suspendisse maximus laoreet ante vitae porttitor. Nulla tincidunt augue eget elementum luctus. Vivamus tincidunt quam nec ipsum sollicitudin vulputate. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In venenatis, eros eget tristique tincidunt, metus leo egestas nibh, vitae tincidunt nisl diam nec metus. Suspendisse potenti. Proin eget ex ullamcorper odio malesuada bibendum ac nec orci. Sed convallis ex sed elit ultrices ullamcorper. Maecenas fermentum consectetur purus id tincidunt."
                    ]
                } as HelpSection, {
                    title: "Help Section 3",
                    content: [
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent interdum placerat justo sit amet viverra. Nullam eget justo sed lacus malesuada scelerisque sed venenatis odio. Pellentesque convallis consectetur dui, quis pellentesque felis consectetur at. Mauris sem elit, tempus vel ligula a, ultricies pellentesque purus. Cras ullamcorper lacinia nisi, vel ornare augue bibendum consequat. Mauris nec molestie dolor. Nullam luctus tortor scelerisque ligula venenatis, vitae malesuada magna pulvinar. Pellentesque et arcu vel felis bibendum tristique. Donec a interdum eros. In molestie purus sollicitudin enim lacinia eleifend. Sed suscipit vehicula felis a lacinia",
                        "Vestibulum quis elit sapien. Quisque maximus auctor varius. Maecenas egestas dolor nulla. Fusce vitae dui non risus malesuada interdum eget id nisl. Nunc suscipit luctus ipsum, nec luctus orci vestibulum ac. Proin pharetra venenatis sollicitudin. Phasellus viverra leo sed pellentesque convallis. Maecenas cursus ultricies neque, vel vestibulum ex eleifend vitae. Curabitur ornare nisi sed convallis condimentum. Cras condimentum ullamcorper varius. Ut quis rhoncus nulla, sit amet aliquam odio. Nullam tincidunt, augue eget tincidunt finibus, eros metus ultrices magna, sed ultricies nisi nisl eget risus. Phasellus pulvinar risus id metus facilisis vulputate. Integer aliquet, ligula consequat ullamcorper condimentum, magna eros pellentesque eros, sed pharetra ligula diam eu nisi. Nulla ut lectus massa. Nulla vitae quam hendrerit, porttitor turpis sed, maximus lacus",
                        "Proin pulvinar lacus tempus vulputate euismod. Mauris nisl arcu, molestie eget varius id, dapibus ac metus. Nam aliquam, massa sed porttitor accumsan, eros magna lobortis lacus, non accumsan dui magna porttitor ligula. Suspendisse maximus laoreet ante vitae porttitor. Nulla tincidunt augue eget elementum luctus. Vivamus tincidunt quam nec ipsum sollicitudin vulputate. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In venenatis, eros eget tristique tincidunt, metus leo egestas nibh, vitae tincidunt nisl diam nec metus. Suspendisse potenti. Proin eget ex ullamcorper odio malesuada bibendum ac nec orci. Sed convallis ex sed elit ultrices ullamcorper. Maecenas fermentum consectetur purus id tincidunt."
                    ]
                } as HelpSection, {
                    title: "Help Section 4",
                    content: [
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent interdum placerat justo sit amet viverra. Nullam eget justo sed lacus malesuada scelerisque sed venenatis odio. Pellentesque convallis consectetur dui, quis pellentesque felis consectetur at. Mauris sem elit, tempus vel ligula a, ultricies pellentesque purus. Cras ullamcorper lacinia nisi, vel ornare augue bibendum consequat. Mauris nec molestie dolor. Nullam luctus tortor scelerisque ligula venenatis, vitae malesuada magna pulvinar. Pellentesque et arcu vel felis bibendum tristique. Donec a interdum eros. In molestie purus sollicitudin enim lacinia eleifend. Sed suscipit vehicula felis a lacinia",
                        "Vestibulum quis elit sapien. Quisque maximus auctor varius. Maecenas egestas dolor nulla. Fusce vitae dui non risus malesuada interdum eget id nisl. Nunc suscipit luctus ipsum, nec luctus orci vestibulum ac. Proin pharetra venenatis sollicitudin. Phasellus viverra leo sed pellentesque convallis. Maecenas cursus ultricies neque, vel vestibulum ex eleifend vitae. Curabitur ornare nisi sed convallis condimentum. Cras condimentum ullamcorper varius. Ut quis rhoncus nulla, sit amet aliquam odio. Nullam tincidunt, augue eget tincidunt finibus, eros metus ultrices magna, sed ultricies nisi nisl eget risus. Phasellus pulvinar risus id metus facilisis vulputate. Integer aliquet, ligula consequat ullamcorper condimentum, magna eros pellentesque eros, sed pharetra ligula diam eu nisi. Nulla ut lectus massa. Nulla vitae quam hendrerit, porttitor turpis sed, maximus lacus",
                        "Proin pulvinar lacus tempus vulputate euismod. Mauris nisl arcu, molestie eget varius id, dapibus ac metus. Nam aliquam, massa sed porttitor accumsan, eros magna lobortis lacus, non accumsan dui magna porttitor ligula. Suspendisse maximus laoreet ante vitae porttitor. Nulla tincidunt augue eget elementum luctus. Vivamus tincidunt quam nec ipsum sollicitudin vulputate. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In venenatis, eros eget tristique tincidunt, metus leo egestas nibh, vitae tincidunt nisl diam nec metus. Suspendisse potenti. Proin eget ex ullamcorper odio malesuada bibendum ac nec orci. Sed convallis ex sed elit ultrices ullamcorper. Maecenas fermentum consectetur purus id tincidunt."
                    ]
                } as HelpSection,
            ]
        case StageEnum.AwardAndUpdate:
            return [
                {
                    title: "Help Section 1",
                    content: [
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent interdum placerat justo sit amet viverra. Nullam eget justo sed lacus malesuada scelerisque sed venenatis odio. Pellentesque convallis consectetur dui, quis pellentesque felis consectetur at. Mauris sem elit, tempus vel ligula a, ultricies pellentesque purus. Cras ullamcorper lacinia nisi, vel ornare augue bibendum consequat. Mauris nec molestie dolor. Nullam luctus tortor scelerisque ligula venenatis, vitae malesuada magna pulvinar. Pellentesque et arcu vel felis bibendum tristique. Donec a interdum eros. In molestie purus sollicitudin enim lacinia eleifend. Sed suscipit vehicula felis a lacinia",
                        "Vestibulum quis elit sapien. Quisque maximus auctor varius. Maecenas egestas dolor nulla. Fusce vitae dui non risus malesuada interdum eget id nisl. Nunc suscipit luctus ipsum, nec luctus orci vestibulum ac. Proin pharetra venenatis sollicitudin. Phasellus viverra leo sed pellentesque convallis. Maecenas cursus ultricies neque, vel vestibulum ex eleifend vitae. Curabitur ornare nisi sed convallis condimentum. Cras condimentum ullamcorper varius. Ut quis rhoncus nulla, sit amet aliquam odio. Nullam tincidunt, augue eget tincidunt finibus, eros metus ultrices magna, sed ultricies nisi nisl eget risus. Phasellus pulvinar risus id metus facilisis vulputate. Integer aliquet, ligula consequat ullamcorper condimentum, magna eros pellentesque eros, sed pharetra ligula diam eu nisi. Nulla ut lectus massa. Nulla vitae quam hendrerit, porttitor turpis sed, maximus lacus",
                        "Proin pulvinar lacus tempus vulputate euismod. Mauris nisl arcu, molestie eget varius id, dapibus ac metus. Nam aliquam, massa sed porttitor accumsan, eros magna lobortis lacus, non accumsan dui magna porttitor ligula. Suspendisse maximus laoreet ante vitae porttitor. Nulla tincidunt augue eget elementum luctus. Vivamus tincidunt quam nec ipsum sollicitudin vulputate. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In venenatis, eros eget tristique tincidunt, metus leo egestas nibh, vitae tincidunt nisl diam nec metus. Suspendisse potenti. Proin eget ex ullamcorper odio malesuada bibendum ac nec orci. Sed convallis ex sed elit ultrices ullamcorper. Maecenas fermentum consectetur purus id tincidunt."
                    ]
                } as HelpSection,
                {
                    title: "Help Section 2",
                    content: [
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent interdum placerat justo sit amet viverra. Nullam eget justo sed lacus malesuada scelerisque sed venenatis odio. Pellentesque convallis consectetur dui, quis pellentesque felis consectetur at. Mauris sem elit, tempus vel ligula a, ultricies pellentesque purus. Cras ullamcorper lacinia nisi, vel ornare augue bibendum consequat. Mauris nec molestie dolor. Nullam luctus tortor scelerisque ligula venenatis, vitae malesuada magna pulvinar. Pellentesque et arcu vel felis bibendum tristique. Donec a interdum eros. In molestie purus sollicitudin enim lacinia eleifend. Sed suscipit vehicula felis a lacinia",
                        "Vestibulum quis elit sapien. Quisque maximus auctor varius. Maecenas egestas dolor nulla. Fusce vitae dui non risus malesuada interdum eget id nisl. Nunc suscipit luctus ipsum, nec luctus orci vestibulum ac. Proin pharetra venenatis sollicitudin. Phasellus viverra leo sed pellentesque convallis. Maecenas cursus ultricies neque, vel vestibulum ex eleifend vitae. Curabitur ornare nisi sed convallis condimentum. Cras condimentum ullamcorper varius. Ut quis rhoncus nulla, sit amet aliquam odio. Nullam tincidunt, augue eget tincidunt finibus, eros metus ultrices magna, sed ultricies nisi nisl eget risus. Phasellus pulvinar risus id metus facilisis vulputate. Integer aliquet, ligula consequat ullamcorper condimentum, magna eros pellentesque eros, sed pharetra ligula diam eu nisi. Nulla ut lectus massa. Nulla vitae quam hendrerit, porttitor turpis sed, maximus lacus",
                        "Proin pulvinar lacus tempus vulputate euismod. Mauris nisl arcu, molestie eget varius id, dapibus ac metus. Nam aliquam, massa sed porttitor accumsan, eros magna lobortis lacus, non accumsan dui magna porttitor ligula. Suspendisse maximus laoreet ante vitae porttitor. Nulla tincidunt augue eget elementum luctus. Vivamus tincidunt quam nec ipsum sollicitudin vulputate. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In venenatis, eros eget tristique tincidunt, metus leo egestas nibh, vitae tincidunt nisl diam nec metus. Suspendisse potenti. Proin eget ex ullamcorper odio malesuada bibendum ac nec orci. Sed convallis ex sed elit ultrices ullamcorper. Maecenas fermentum consectetur purus id tincidunt."
                    ]
                } as HelpSection, {
                    title: "Help Section 3",
                    content: [
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent interdum placerat justo sit amet viverra. Nullam eget justo sed lacus malesuada scelerisque sed venenatis odio. Pellentesque convallis consectetur dui, quis pellentesque felis consectetur at. Mauris sem elit, tempus vel ligula a, ultricies pellentesque purus. Cras ullamcorper lacinia nisi, vel ornare augue bibendum consequat. Mauris nec molestie dolor. Nullam luctus tortor scelerisque ligula venenatis, vitae malesuada magna pulvinar. Pellentesque et arcu vel felis bibendum tristique. Donec a interdum eros. In molestie purus sollicitudin enim lacinia eleifend. Sed suscipit vehicula felis a lacinia",
                        "Vestibulum quis elit sapien. Quisque maximus auctor varius. Maecenas egestas dolor nulla. Fusce vitae dui non risus malesuada interdum eget id nisl. Nunc suscipit luctus ipsum, nec luctus orci vestibulum ac. Proin pharetra venenatis sollicitudin. Phasellus viverra leo sed pellentesque convallis. Maecenas cursus ultricies neque, vel vestibulum ex eleifend vitae. Curabitur ornare nisi sed convallis condimentum. Cras condimentum ullamcorper varius. Ut quis rhoncus nulla, sit amet aliquam odio. Nullam tincidunt, augue eget tincidunt finibus, eros metus ultrices magna, sed ultricies nisi nisl eget risus. Phasellus pulvinar risus id metus facilisis vulputate. Integer aliquet, ligula consequat ullamcorper condimentum, magna eros pellentesque eros, sed pharetra ligula diam eu nisi. Nulla ut lectus massa. Nulla vitae quam hendrerit, porttitor turpis sed, maximus lacus",
                        "Proin pulvinar lacus tempus vulputate euismod. Mauris nisl arcu, molestie eget varius id, dapibus ac metus. Nam aliquam, massa sed porttitor accumsan, eros magna lobortis lacus, non accumsan dui magna porttitor ligula. Suspendisse maximus laoreet ante vitae porttitor. Nulla tincidunt augue eget elementum luctus. Vivamus tincidunt quam nec ipsum sollicitudin vulputate. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In venenatis, eros eget tristique tincidunt, metus leo egestas nibh, vitae tincidunt nisl diam nec metus. Suspendisse potenti. Proin eget ex ullamcorper odio malesuada bibendum ac nec orci. Sed convallis ex sed elit ultrices ullamcorper. Maecenas fermentum consectetur purus id tincidunt."
                    ]
                } as HelpSection, {
                    title: "Help Section 4",
                    content: [
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent interdum placerat justo sit amet viverra. Nullam eget justo sed lacus malesuada scelerisque sed venenatis odio. Pellentesque convallis consectetur dui, quis pellentesque felis consectetur at. Mauris sem elit, tempus vel ligula a, ultricies pellentesque purus. Cras ullamcorper lacinia nisi, vel ornare augue bibendum consequat. Mauris nec molestie dolor. Nullam luctus tortor scelerisque ligula venenatis, vitae malesuada magna pulvinar. Pellentesque et arcu vel felis bibendum tristique. Donec a interdum eros. In molestie purus sollicitudin enim lacinia eleifend. Sed suscipit vehicula felis a lacinia",
                        "Vestibulum quis elit sapien. Quisque maximus auctor varius. Maecenas egestas dolor nulla. Fusce vitae dui non risus malesuada interdum eget id nisl. Nunc suscipit luctus ipsum, nec luctus orci vestibulum ac. Proin pharetra venenatis sollicitudin. Phasellus viverra leo sed pellentesque convallis. Maecenas cursus ultricies neque, vel vestibulum ex eleifend vitae. Curabitur ornare nisi sed convallis condimentum. Cras condimentum ullamcorper varius. Ut quis rhoncus nulla, sit amet aliquam odio. Nullam tincidunt, augue eget tincidunt finibus, eros metus ultrices magna, sed ultricies nisi nisl eget risus. Phasellus pulvinar risus id metus facilisis vulputate. Integer aliquet, ligula consequat ullamcorper condimentum, magna eros pellentesque eros, sed pharetra ligula diam eu nisi. Nulla ut lectus massa. Nulla vitae quam hendrerit, porttitor turpis sed, maximus lacus",
                        "Proin pulvinar lacus tempus vulputate euismod. Mauris nisl arcu, molestie eget varius id, dapibus ac metus. Nam aliquam, massa sed porttitor accumsan, eros magna lobortis lacus, non accumsan dui magna porttitor ligula. Suspendisse maximus laoreet ante vitae porttitor. Nulla tincidunt augue eget elementum luctus. Vivamus tincidunt quam nec ipsum sollicitudin vulputate. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In venenatis, eros eget tristique tincidunt, metus leo egestas nibh, vitae tincidunt nisl diam nec metus. Suspendisse potenti. Proin eget ex ullamcorper odio malesuada bibendum ac nec orci. Sed convallis ex sed elit ultrices ullamcorper. Maecenas fermentum consectetur purus id tincidunt."
                    ]
                } as HelpSection,
            ]
        case StageEnum.Report:
            return [
                {
                    title: "Help Section 1",
                    content: [
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent interdum placerat justo sit amet viverra. Nullam eget justo sed lacus malesuada scelerisque sed venenatis odio. Pellentesque convallis consectetur dui, quis pellentesque felis consectetur at. Mauris sem elit, tempus vel ligula a, ultricies pellentesque purus. Cras ullamcorper lacinia nisi, vel ornare augue bibendum consequat. Mauris nec molestie dolor. Nullam luctus tortor scelerisque ligula venenatis, vitae malesuada magna pulvinar. Pellentesque et arcu vel felis bibendum tristique. Donec a interdum eros. In molestie purus sollicitudin enim lacinia eleifend. Sed suscipit vehicula felis a lacinia",
                        "Vestibulum quis elit sapien. Quisque maximus auctor varius. Maecenas egestas dolor nulla. Fusce vitae dui non risus malesuada interdum eget id nisl. Nunc suscipit luctus ipsum, nec luctus orci vestibulum ac. Proin pharetra venenatis sollicitudin. Phasellus viverra leo sed pellentesque convallis. Maecenas cursus ultricies neque, vel vestibulum ex eleifend vitae. Curabitur ornare nisi sed convallis condimentum. Cras condimentum ullamcorper varius. Ut quis rhoncus nulla, sit amet aliquam odio. Nullam tincidunt, augue eget tincidunt finibus, eros metus ultrices magna, sed ultricies nisi nisl eget risus. Phasellus pulvinar risus id metus facilisis vulputate. Integer aliquet, ligula consequat ullamcorper condimentum, magna eros pellentesque eros, sed pharetra ligula diam eu nisi. Nulla ut lectus massa. Nulla vitae quam hendrerit, porttitor turpis sed, maximus lacus",
                        "Proin pulvinar lacus tempus vulputate euismod. Mauris nisl arcu, molestie eget varius id, dapibus ac metus. Nam aliquam, massa sed porttitor accumsan, eros magna lobortis lacus, non accumsan dui magna porttitor ligula. Suspendisse maximus laoreet ante vitae porttitor. Nulla tincidunt augue eget elementum luctus. Vivamus tincidunt quam nec ipsum sollicitudin vulputate. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In venenatis, eros eget tristique tincidunt, metus leo egestas nibh, vitae tincidunt nisl diam nec metus. Suspendisse potenti. Proin eget ex ullamcorper odio malesuada bibendum ac nec orci. Sed convallis ex sed elit ultrices ullamcorper. Maecenas fermentum consectetur purus id tincidunt."
                    ]
                } as HelpSection,
                {
                    title: "Help Section 2",
                    content: [
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent interdum placerat justo sit amet viverra. Nullam eget justo sed lacus malesuada scelerisque sed venenatis odio. Pellentesque convallis consectetur dui, quis pellentesque felis consectetur at. Mauris sem elit, tempus vel ligula a, ultricies pellentesque purus. Cras ullamcorper lacinia nisi, vel ornare augue bibendum consequat. Mauris nec molestie dolor. Nullam luctus tortor scelerisque ligula venenatis, vitae malesuada magna pulvinar. Pellentesque et arcu vel felis bibendum tristique. Donec a interdum eros. In molestie purus sollicitudin enim lacinia eleifend. Sed suscipit vehicula felis a lacinia",
                        "Vestibulum quis elit sapien. Quisque maximus auctor varius. Maecenas egestas dolor nulla. Fusce vitae dui non risus malesuada interdum eget id nisl. Nunc suscipit luctus ipsum, nec luctus orci vestibulum ac. Proin pharetra venenatis sollicitudin. Phasellus viverra leo sed pellentesque convallis. Maecenas cursus ultricies neque, vel vestibulum ex eleifend vitae. Curabitur ornare nisi sed convallis condimentum. Cras condimentum ullamcorper varius. Ut quis rhoncus nulla, sit amet aliquam odio. Nullam tincidunt, augue eget tincidunt finibus, eros metus ultrices magna, sed ultricies nisi nisl eget risus. Phasellus pulvinar risus id metus facilisis vulputate. Integer aliquet, ligula consequat ullamcorper condimentum, magna eros pellentesque eros, sed pharetra ligula diam eu nisi. Nulla ut lectus massa. Nulla vitae quam hendrerit, porttitor turpis sed, maximus lacus",
                        "Proin pulvinar lacus tempus vulputate euismod. Mauris nisl arcu, molestie eget varius id, dapibus ac metus. Nam aliquam, massa sed porttitor accumsan, eros magna lobortis lacus, non accumsan dui magna porttitor ligula. Suspendisse maximus laoreet ante vitae porttitor. Nulla tincidunt augue eget elementum luctus. Vivamus tincidunt quam nec ipsum sollicitudin vulputate. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In venenatis, eros eget tristique tincidunt, metus leo egestas nibh, vitae tincidunt nisl diam nec metus. Suspendisse potenti. Proin eget ex ullamcorper odio malesuada bibendum ac nec orci. Sed convallis ex sed elit ultrices ullamcorper. Maecenas fermentum consectetur purus id tincidunt."
                    ]
                } as HelpSection, {
                    title: "Help Section 3",
                    content: [
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent interdum placerat justo sit amet viverra. Nullam eget justo sed lacus malesuada scelerisque sed venenatis odio. Pellentesque convallis consectetur dui, quis pellentesque felis consectetur at. Mauris sem elit, tempus vel ligula a, ultricies pellentesque purus. Cras ullamcorper lacinia nisi, vel ornare augue bibendum consequat. Mauris nec molestie dolor. Nullam luctus tortor scelerisque ligula venenatis, vitae malesuada magna pulvinar. Pellentesque et arcu vel felis bibendum tristique. Donec a interdum eros. In molestie purus sollicitudin enim lacinia eleifend. Sed suscipit vehicula felis a lacinia",
                        "Vestibulum quis elit sapien. Quisque maximus auctor varius. Maecenas egestas dolor nulla. Fusce vitae dui non risus malesuada interdum eget id nisl. Nunc suscipit luctus ipsum, nec luctus orci vestibulum ac. Proin pharetra venenatis sollicitudin. Phasellus viverra leo sed pellentesque convallis. Maecenas cursus ultricies neque, vel vestibulum ex eleifend vitae. Curabitur ornare nisi sed convallis condimentum. Cras condimentum ullamcorper varius. Ut quis rhoncus nulla, sit amet aliquam odio. Nullam tincidunt, augue eget tincidunt finibus, eros metus ultrices magna, sed ultricies nisi nisl eget risus. Phasellus pulvinar risus id metus facilisis vulputate. Integer aliquet, ligula consequat ullamcorper condimentum, magna eros pellentesque eros, sed pharetra ligula diam eu nisi. Nulla ut lectus massa. Nulla vitae quam hendrerit, porttitor turpis sed, maximus lacus",
                        "Proin pulvinar lacus tempus vulputate euismod. Mauris nisl arcu, molestie eget varius id, dapibus ac metus. Nam aliquam, massa sed porttitor accumsan, eros magna lobortis lacus, non accumsan dui magna porttitor ligula. Suspendisse maximus laoreet ante vitae porttitor. Nulla tincidunt augue eget elementum luctus. Vivamus tincidunt quam nec ipsum sollicitudin vulputate. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In venenatis, eros eget tristique tincidunt, metus leo egestas nibh, vitae tincidunt nisl diam nec metus. Suspendisse potenti. Proin eget ex ullamcorper odio malesuada bibendum ac nec orci. Sed convallis ex sed elit ultrices ullamcorper. Maecenas fermentum consectetur purus id tincidunt."
                    ]
                } as HelpSection, {
                    title: "Help Section 4",
                    content: [
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent interdum placerat justo sit amet viverra. Nullam eget justo sed lacus malesuada scelerisque sed venenatis odio. Pellentesque convallis consectetur dui, quis pellentesque felis consectetur at. Mauris sem elit, tempus vel ligula a, ultricies pellentesque purus. Cras ullamcorper lacinia nisi, vel ornare augue bibendum consequat. Mauris nec molestie dolor. Nullam luctus tortor scelerisque ligula venenatis, vitae malesuada magna pulvinar. Pellentesque et arcu vel felis bibendum tristique. Donec a interdum eros. In molestie purus sollicitudin enim lacinia eleifend. Sed suscipit vehicula felis a lacinia",
                        "Vestibulum quis elit sapien. Quisque maximus auctor varius. Maecenas egestas dolor nulla. Fusce vitae dui non risus malesuada interdum eget id nisl. Nunc suscipit luctus ipsum, nec luctus orci vestibulum ac. Proin pharetra venenatis sollicitudin. Phasellus viverra leo sed pellentesque convallis. Maecenas cursus ultricies neque, vel vestibulum ex eleifend vitae. Curabitur ornare nisi sed convallis condimentum. Cras condimentum ullamcorper varius. Ut quis rhoncus nulla, sit amet aliquam odio. Nullam tincidunt, augue eget tincidunt finibus, eros metus ultrices magna, sed ultricies nisi nisl eget risus. Phasellus pulvinar risus id metus facilisis vulputate. Integer aliquet, ligula consequat ullamcorper condimentum, magna eros pellentesque eros, sed pharetra ligula diam eu nisi. Nulla ut lectus massa. Nulla vitae quam hendrerit, porttitor turpis sed, maximus lacus",
                        "Proin pulvinar lacus tempus vulputate euismod. Mauris nisl arcu, molestie eget varius id, dapibus ac metus. Nam aliquam, massa sed porttitor accumsan, eros magna lobortis lacus, non accumsan dui magna porttitor ligula. Suspendisse maximus laoreet ante vitae porttitor. Nulla tincidunt augue eget elementum luctus. Vivamus tincidunt quam nec ipsum sollicitudin vulputate. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In venenatis, eros eget tristique tincidunt, metus leo egestas nibh, vitae tincidunt nisl diam nec metus. Suspendisse potenti. Proin eget ex ullamcorper odio malesuada bibendum ac nec orci. Sed convallis ex sed elit ultrices ullamcorper. Maecenas fermentum consectetur purus id tincidunt."
                    ]
                } as HelpSection,
            ]
        default:
            return [{
                title: "Bridge your Ethereum to OEV Network.",
                content: ["You can add funds to your wallet by using the official OEV Network bridge."]
            } as HelpSection]
    }
}