# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy to Github Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pack-and-deploy-to-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.12.1
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: 'pnpm'
      - name: Install Packages
        run: pnpm install 
      - name: Build Package
        run: pnpm run build
      - name: Deploy to Github Pages
        if : github.ref == 'refs/heads/main' || contains(github.event.pull_request.labels.*.name, 'deploy')
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ./build